### ISSUE TITLE
Can't connect MQTT with SSL/TLS in iOS

### ISSUE THREAD

**Issue by mazidahmad** [gojek/courier-flutter#11]
Hi, I want to report an issue when I want to connect MQTT with SSL/TLS scheme. I just try to connect and reach the connect timeout. If I see from the code, the SSL connection will active if the port connection is only 443. Can it be more dynamic?

<img width="1010" alt="image" src="https://github.com/gojek/courier-flutter/assets/45102623/e32b409b-e88e-4354-91e8-3c2a8c3c7c26">

<img width="885" alt="image" src="https://github.com/gojek/courier-flutter/assets/45102623/aff4a104-3433-4c0b-a623-fa5ba0c44939">

**Comment by alfianlosari** [comment]
This is now supported with this merged PR https://github.com/gojek/courier-flutter/pull/13
